In [1]:
import torch
from DDPG import QFunction

/home/gekeleda/mambaforge/envs/rl/lib/python3.8/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: ''If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
/home/gekeleda/mambaforge/envs/rl/lib/python3.8/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


using xpu device


In [2]:
Q = QFunction(1, 1)

In [3]:
o = torch.rand((1,1)).to(torch.device('xpu:0'), dtype=torch.bfloat16)
a = torch.rand((1,1)).to(torch.device('xpu:0'), dtype=torch.bfloat16)
t = torch.rand((1,1)).to(torch.device('xpu:0'), dtype=torch.bfloat16)
# o = torch.rand((128,1)).to(torch.device('cpu'), dtype=torch.bfloat16)
# a = torch.rand((128,1)).to(torch.device('cpu'), dtype=torch.bfloat16)
# t = torch.rand((128,1)).to(torch.device('cpu'), dtype=torch.bfloat16)
o, a, t

(tensor([[0.7344]], device='xpu:0', dtype=torch.bfloat16),
 tensor([[0.2412]], device='xpu:0', dtype=torch.bfloat16),
 tensor([[0.7383]], device='xpu:0', dtype=torch.bfloat16))

In [4]:
q = Q.Q_value(o, a)
q

tensor([[0.1904]], device='xpu:0', dtype=torch.bfloat16,
       grad_fn=<AddmmBackward0>)

In [5]:
loss_val = Q.loss(q, t)
loss_val

tensor(0.1494, device='xpu:0', dtype=torch.bfloat16,
       grad_fn=<SmoothL1LossBackward0>)

In [6]:
loss_val.backward()

RuntimeError: could not execute a primitive

In [ ]:
Q.fit(o, a, t)

observations:  torch.Size([128, 1]) torch.bfloat16 cpu
actions:  torch.Size([128, 1]) torch.bfloat16 cpu
targets:  torch.Size([128, 1]) torch.bfloat16 cpu


0.18359375